/zed/zed_node:
  ros__parameters:
    "":
      zed_node:
        depth:
          depth_registered:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        left:
          image_rect_color:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        left_gray:
          image_rect_gray:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        left_raw:
          image_raw_color:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        left_raw_gray:
          image_raw_gray:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        point_cloud:
          cloud_registered:
            draco:
              attribute_mapping:
                attribute_type:
                  x: POSITION
                  y: POSITION
                  z: POSITION
                quantization_bits:
                  rgb: 16
                  x: 16
                  y: 16
                  z: 16
                rgba_tweak:
                  rgb: true
                  rgba: false
              decode_speed: 7
              deduplicate: true
              encode_method: 0
              encode_speed: 7
              expert_attribute_types: false
              expert_quantization: false
              force_quantization: false
              quantization_COLOR: 14
              quantization_GENERIC: 14
              quantization_NORMAL: 14
              quantization_POSITION: 14
              quantization_TEX_COORD: 14
            zlib:
              encode_level: 7
            zstd:
              zstd_encode_level: 7
        rgb_gray:
          image_rect_gray:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        rgb_raw:
          image_raw_color:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        rgb_raw_gray:
          image_raw_gray:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        right:
          image_rect_color:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        right_gray:
          image_rect_gray:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        right_raw:
          image_raw_color:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        right_raw_gray:
          image_raw_gray:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        stereo:
          image_rect_color:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        stereo_raw:
          image_raw_color:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
    advanced:
      thread_sched_policy: SCHED_BATCH
    body_tracking:
      allow_reduced_precision_inference: false
      body_format: BODY_38
      body_kp_selection: FULL
      bt_enabled: false
      confidence_threshold: 50.0
      enable_body_fitting: false
      enable_tracking: true
      max_range: 20.0
      minimum_keypoints_threshold: 5
      model: HUMAN_BODY_MEDIUM
      prediction_timeout_s: 0.5
    debug:
      debug_advanced: false
      debug_body_tracking: false
      debug_camera_controls: false
      debug_common: false
      debug_gnss: false
      debug_mapping: false
      debug_object_detection: false
      debug_point_cloud: false
      debug_positional_tracking: false
      debug_roi: false
      debug_sensors: false
      debug_sim: false
      debug_streaming: false
      debug_video_depth: false
      sdk_verbose: 0
    depth:
      depth_confidence: 80
      depth_mode: NEURAL_LIGHT
      depth_stabilization: 10
      depth_texture_conf: 80
      max_depth: 2.0
      min_depth: 0.3
      openni_depth_mode: false
      point_cloud_freq: 10.0
      point_cloud_res: COMPACT
      remove_saturated_areas: true
    diagnostic_updater:
      period: 1.0
      use_fqn: false
    general:
      async_image_retrieval: false
      camera_flip: false
      camera_id: -1
      camera_max_reconnect: 5
      camera_model: zedm
      camera_name: zed
      camera_timeout_sec: 45
      gpu_id: 0
      grab_frame_rate: 15
      grab_resolution: VGA
      optional_opencv_calibration_file: ""
      pub_downscale_factor: 1.0
      pub_frame_rate: 15.0
      pub_resolution: NATIVE
      self_calib: true
      serial_number: 0
    gnss_fusion:
      gnss_fusion_enabled: false
    mapping:
      clicked_point_topic: /clicked_point
      fused_pointcloud_freq: 1.0
      mapping_enabled: false
      max_mapping_range: 5.0
      pd_max_distance_threshold: 0.15
      pd_normal_similarity_threshold: 15.0
      resolution: 0.05
    object_detection:
      allow_reduced_precision_inference: true
      confidence_threshold: 50.0
      filtering_mode: 2
      max_range: 2.0
      model: MULTI_CLASS_BOX_FAST
      object_tracking_enabled: true
      od_enabled: true
      prediction_timeout: 2.0
      mc_people: true
      mc_vehicle: false
      mc_bag: false
      mc_animal: false
      mc_electronics: false
      mc_fruit_vegetable: false
      mc_sport: false
    pos_tracking:
      area_memory: false
      area_memory_db_path: ""
      depth_min_range: 0.4
      floor_alignment: false
      imu_fusion: true
      initial_base_pose:
        - 0.174
        - 0.0
        - 0.746
        - 0.0
        - 0.523
        - 0.0
      map_frame: map
      odometry_frame: odom
      path_max_count: 50
      path_pub_rate: 1.0
      pos_tracking_enabled: true
      pos_tracking_mode: GEN_2
      publish_map_tf: false
      publish_tf: false
      reset_odom_with_loop_closure: false
      reset_pose_with_svo_loop: false
      set_as_static: false
      set_gravity_as_origin: false
      transform_time_offset: 0.0
      two_d_mode: false
  qos_overrides:
    /clicked_point:
      subscription:
        depth: 10
        history: keep_last
        reliability: reliable
    /parameter_events:
      publisher:
        depth: 10
        durability: volatile
        history: keep_last
        reliability: reliable
    /tf:
      publisher:
        depth: 10
        durability: volatile
        history: keep_last
        reliability: reliable
    /zed/plane:
      publisher:
        depth: 10
        history: keep_last
        reliability: reliable
    /zed/plane_marker:
      publisher:
        depth: 10
        history: keep_last
        reliability: reliable
    /zed/zed_node/depth/depth_info:
      publisher:
        depth: 10
        history: keep_last
        reliability: reliable
    /zed/zed_node/disparity/disparity_image:
      publisher:
        depth: 10
        history: keep_last
        reliability: reliable
    /zed/zed_node/imu/data:
      publisher:
        depth: 10
        history: keep_last
        reliability: reliable
    /zed/zed_node/imu/data_raw:
      publisher:
        depth: 10
        history: keep_last
        reliability: reliable
    /zed/zed_node/left_cam_imu_transform:
      publisher:
        depth: 10
        history: keep_last
        reliability: reliable
    /zed/zed_node/obj_det/objects:
      publisher:
        depth: 5
        history: keep_last
        reliability: reliable
    /zed/zed_node/odom:
      publisher:
        depth: 1
        history: keep_last
        reliability: reliable
    /zed/zed_node/path_map:
      publisher:
        depth: 5
        history: keep_last
        reliability: reliable
    /zed/zed_node/path_odom:
      publisher:
        depth: 5
        history: keep_last
        reliability: reliable
    /zed/zed_node/point_cloud/cloud_registered:
      publisher:
        depth: 1
        history: keep_last
        reliability: reliable
    /zed/zed_node/point_cloud/cloud_registered/draco:
      publisher:
        depth: 1
        history: keep_last
        reliability: reliable
    /zed/zed_node/point_cloud/cloud_registered/zlib:
      publisher:
        depth: 10
        history: keep_last
        reliability: reliable
    /zed/zed_node/point_cloud/cloud_registered/zstd:
      publisher:
        depth: 10
        history: keep_last
        reliability: reliable
    /zed/zed_node/pose:
      publisher:
        depth: 1
        history: keep_last
        reliability: reliable
    /zed/zed_node/pose/status:
      publisher:
        depth: 10
        history: keep_last
        reliability: reliable
    /zed/zed_node/pose_with_covariance:
      publisher:
        depth: 10
        history: keep_last
        reliability: reliable
  region_of_interest:
    automatic_roi: false
    manual_polygon: "[]"
  sensors:
    publish_imu_tf: false
    sensors_image_sync: false
    sensors_pub_rate: 1.0
  simulation:
    sim_enabled: false
  stream:
    stream_address: ""
  stream_server:
    adaptative_bitrate: false
    bitrate: 12500
    chunk_size: 16084
    codec: H264
    gop_size: -1
    port: 30000
    stream_enabled: false
    target_framerate: 0
  svo:
    svo_path: live
  use_sim_time: false
  video:
    auto_exposure_gain: true
    auto_whitebalance: true
    brightness: 4
    contrast: 4
    exposure: 80
    gain: 80
    gamma: 8
    hue: 0
    saturation: 4
    sharpness: 4
    whitebalance_temperature: 42
  zed_node:
    depth:
      depth_registered:
        enable_pub_plugins:
          - image_transport/compressed
          - image_transport/raw
        ffmpeg:
          bit_rate: -1
          encoder: libx264
          encoder_av_options: ""
          encoder_measure_performance: false
          gop_size: -1
          max_b_frames: 0
          pixel_format: ""
          qmax: -1
    point_cloud:
      cloud_registered:
        enable_pub_plugins:
          - point_cloud_transport/draco
          - point_cloud_transport/raw
    rgb:
      image_rect_color:
        enable_pub_plugins:
          - image_transport/raw
          - image_transport/compressed
        compressed:
          format: jpeg
          jpeg_quality: 70
