twist_mux:
  ros__parameters:
    # Output topic (this is what your controller subscribes to)
    output_topic: /cmd_vel_out
    qos_overrides:
      /cmd_vel_out:
        publisher:
          reliability: best_effort
          durability: volatile
          history: keep_last
          depth: 1

    # Timeout after which a source is considered inactive (seconds)
    timeout: 0.5

    topics:
      joystick:
        topic: /cmd_vel_joy
        timeout: 0.5
        priority: 100

      pid:
        topic: /cmd_vel_pid
        timeout: 0.5
        priority: 10
